name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: soranest
  SERVICE_NAME: soranest-tools
  REGION: asia-northeast1
  REPO_NAME: soranest-tools

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and Deploy to Cloud Run
      run: |-
        # 构建镜像
        docker build -t asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        
        # 推送镜像
        docker push asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        
        # 部署到 Cloud Run
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --image asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets="FIREBASE_SERVICE_ACCOUNT_KEY=projects/849883756716/secrets/soranest-backend-json:latest" \
          --memory 512Mi \
          --timeout 300 \

    - name: Clean up
      run: rm -f .env
