name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_CLOUD_RUN_KEY }}
        project_id: lyra-backend-425003

    - name: Authenticate Docker to Google Cloud
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/lyra-backend-425003/semopdfwatermark:latest .
        docker push gcr.io/lyra-backend-425003/semopdfwatermark:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy semopdfwatermark \
          --image gcr.io/lyra-backend-425003/semopdfwatermark:latest \
          --platform managed \
          --region asia-northeast1 \
          --service-account lyra-backend@lyra-backend-425003.iam.gserviceaccount.com \
          --allow-unauthenticated \
          --port 8080 \
          --timeout 10m \
          --cpu 1 \
          --memory 1Gi \
          --concurrency 10

