name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: soranest
  SERVICE_NAME: soranest-tools
  REGION: asia-northeast1
  REPO_NAME: soranest-tools

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Verify permissions
      run: |
        echo "Checking current project:"
        gcloud config get-value project
        echo "Checking authentication:"
        gcloud auth list
        echo "Checking Artifact Registry permissions:"
        gcloud artifacts repositories list --location=${{ env.REGION }} || echo "No repositories found"

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

    - name: Create Artifact Registry repository if not exists
      run: |
        gcloud artifacts repositories create ${{ env.REPO_NAME }} \
          --repository-format=docker \
          --location=${{ env.REGION }} \
          --description="Docker repository for ${{ env.SERVICE_NAME }}" \
          --quiet || echo "Repository already exists"

    - name: Build and Deploy to Cloud Run
      run: |-
        # 构建镜像
        docker build -t asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        
        # 推送镜像
        docker push asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        
        # 部署到 Cloud Run
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --image asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets="FIREBASE_SERVICE_ACCOUNT_KEY=projects/849883756716/secrets/soranest-backend-json:latest" \
          --memory 512Mi \
          --timeout 300

    - name: Clean up
      run: rm -f .env
